services:
  - type: web
    name: yellowroam
    env: python
    startCommand: gunicorn prototype.app:app
    buildCommand: pip install -r prototype/requirements.txt   
    region: oregon
    autoDeploy: true

  
