services:
  - type: web
    name: yellowroam
    env: python
    autoDeploy: true
    region: oregon
    build:
      cwd: prototype
    start:
      cwd: prototype
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
