services:
  - type: web
    name: yellowroam
    env: python
    region: oregon
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    build:
      cwd: prototype
    start:
      cwd: prototype
