services:
  - type: web
    name: yellowroam-backend


    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn prototype.app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production

    name: yellowroam

(Keep local script, restore config.py, and update render.yaml)
    env: python
    region: oregon

    build:
      cwd: prototype
    start:
      cwd: prototype
    buildCommand: pip install -r requirements.txt   # ← just this!
    startCommand: gunicorn app:app
    fb568a5 (Initial commit with Flask app and config setup)

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn prototype.app:app

    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
(Keep local script, restore config.py, and update render.yaml)
